### ISSUE TITLE
Doc suggestion: "workspace addresses" instead of "addresses"

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-graphql#2]
Earthstar has "author addresses" and "workspace addresses" so it can be confusing to just say "addresses".

Example

> `function makeMemoryContext(addresses: string[]): Context;`
> Creates a GraphQL context which stores workspace data in-memory.

Maybe the variable could be `workspaceAddresses`?

(Also would be nice to say "stores data from *multiple* workspaces in-memory")

**Comment by sgwilym** [comment]
Makes total sense, will make those changes.
